CREATE EXTENSION IF NOT EXISTS "uuid-ossp";


CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    avatarUrl TEXT,
    role VARCHAR(255) DEFAULT 'user',
    code INT DEFAULT '',
    codeExpired TIMESTAMP DEFAULT CURRENT_TIMESTAMP + INTERVAL '5 MINUTES'
);
